### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by nasirkhan** [pepiuox/PHP-GrapesJS#1]
Thanks for creating this php implementation. I was trying to use this project. I was wondering if you have implemented the image upload feature and or what is your thoughts on this? specially if it is needed to implement the access control over the files. 

Do you have any doc of this project?

**Comment by pepiuox** [comment]
Hello Nasirkhan,
I am doing an implementation to upload other types of files, for now it is only for images.
I'm really advancing it along with other projects, so I share the development in others, but then I will be publishing updates.
At the moment I do not do documentation due to lack of time.

**Comment by pepiuox** [comment]
> 
> 
> Thanks for creating this php implementation. I was trying to use this project. I was wondering if you have implemented the image upload feature and or what is your thoughts on this? specially if it is needed to implement the access control over the files.
> 
> Do you have any doc of this project?

**specially if it is needed to implement the access control over the files.**

All the images that you add will go up to the UPLOADS folder, when you create content you will be able to see in the image editor everything that is in the UPLOADS folder.
