### ISSUE TITLE
Undeclared Variables I Included

### ISSUE THREAD

**Issue by pedroestevaodev** [pepiuox/PHP-GrapesJS#10]
I recently downloaded the update and came across loose variables. (**Page: start.php**)
This error is also repeated on other pages of the system.

![Captura de tela 2021-09-11 215928](https://user-images.githubusercontent.com/61397405/132967261-84a8b93f-4106-445e-8d37-2e6ce1c68576.jpg)

**Comment by pepiuox** [comment]
> 
> 
> I recently downloaded the update and came across loose variables. (**Page: start.php**)
> This error is also repeated on other pages of the system.
> 
> ![Captura de tela 2021-09-11 215928](https://user-images.githubusercontent.com/61397405/132967261-84a8b93f-4106-445e-8d37-2e6ce1c68576.jpg)

The sql file of the configuration was updated.
