### ISSUE TITLE
Error with GrapesJS

### ISSUE THREAD

**Issue by pedroestevaodev** [pepiuox/PHP-GrapesJS#12]
For some reason the page editor does not start when clicking edit page.

![Captura de tela 2021-09-12 203249](https://user-images.githubusercontent.com/61397405/133006255-a2891740-70b5-4e76-a35d-ca12dccb25de.jpg)

**Comment by pepiuox** [comment]
> 
> 
> For some reason the page editor does not start when clicking edit page.
> 
> ![Captura de tela 2021-09-12 203249](https://user-images.githubusercontent.com/61397405/133006255-a2891740-70b5-4e76-a35d-ca12dccb25de.jpg)

what is the browser you are using? to see if there are any faults with the one you use.

**Comment by pedroestevaodev** [comment]
Estou utilizando o Google Chrome e de fato é estranho. Quando mudo a extensão da página para `.html` e comento o `PHP` o editor aparece normalmente. Será um conflito com o próprio `PHP`? ?

![Captura de tela 2021-09-14 165127](https://user-images.githubusercontent.com/61397405/133324459-27a0ea37-ed08-4555-bb3d-49098edcf6ce.jpg)

Era assim que deveria parecer? ?
-- qual navegador está utilizando para desenvolver? ?

**Comment by pepiuox** [comment]
> Estou utilizando o Google Chrome e de fato é estranho. Quando mudo a extensão da página para `.html` e comento o `PHP` o editor aparece normalmente. Será um conflito com o próprio

It is tested in Chrome and works very well, the same as Brave and Firefox.  
![2021-09-14_17-48-16](https://user-images.githubusercontent.com/5951141/133343997-aaa46cef-ca44-4eaf-80ec-79bf95f4d841.png)

**Comment by pedroestevaodev** [comment]
Consegui resolver, estava colocando o nome do diretório errado na hora da configuração. Agora está criando e abrindo o editor normalmente. Mas agora está ocorrendo o seguinte: quando instalo na raiz do local host a visualização da página criada acontece normalmente. Porém, se eu instalo dentro de uma pasta como "localhost/grape" quando clico em visualizar ele manda diretamente para a raiz do localhost, mesmo estando no config estar todo o caminho corretamente.

**Comment by pedroestevaodev** [comment]
Os erros que estão acontecendo(Com o sistema instalado em uma subpasta) são:

-> Quando clico no View Page
![Captura de tela 2021-09-15 122730](https://user-images.githubusercontent.com/61397405/133463526-64ab5189-8c8a-454a-815f-88ee55e29194.jpg)
=> Ocorre isso:
![Captura de tela 2021-09-15 122215](https://user-images.githubusercontent.com/61397405/133463485-6908ea4a-c739-4a25-a09f-6757426fa8ff.jpg)


-> Quando clico nas seguintes áreas
![Captura de tela 2021-09-15 122852](https://user-images.githubusercontent.com/61397405/133463877-f25923dc-053d-4f00-9e6b-a6fd533202d3.jpg)
![Captura de tela 2021-09-15 122835](https://user-images.githubusercontent.com/61397405/133463882-07c0dba2-2db0-40f9-8fac-beeee107ce45.jpg)
=> Ele leva para a raíz do localhost:
![Captura de tela 2021-09-15 122913](https://user-images.githubusercontent.com/61397405/133464074-1889bb7e-184d-45ec-b56d-829094a11788.jpg)

-> Porém as configurações de diretório estão apontando para o subpasta onde instalei o sistema:
![Captura de tela 2021-09-15 123613](https://user-images.githubusercontent.com/61397405/133464567-b3c0995b-78c1-4dfb-9cda-0a2a386de3f6.jpg)
![Captura de tela 2021-09-15 123549](https://user-images.githubusercontent.com/61397405/133464569-2119348f-7bad-48d7-ad96-ab69c1737955.jpg)

**Comment by pepiuox** [comment]
> 
> 
> Os erros que estão acontecendo(Com o sistema instalado em uma subpasta) são:
> 
> -> Quando clico no View Page
> ![Captura de tela 2021-09-15 122730](https://user-images.githubusercontent.com/61397405/133463526-64ab5189-8c8a-454a-815f-88ee55e29194.jpg)
> => Ocorre isso:
> ![Captura de tela 2021-09-15 122215](https://user-images.githubusercontent.com/61397405/133463485-6908ea4a-c739-4a25-a09f-6757426fa8ff.jpg)
> 
> -> Quando clico nas seguintes áreas
> ![Captura de tela 2021-09-15 122852](https://user-images.githubusercontent.com/61397405/133463877-f25923dc-053d-4f00-9e6b-a6fd533202d3.jpg)
> ![Captura de tela 2021-09-15 122835](https://user-images.githubusercontent.com/61397405/133463882-07c0dba2-2db0-40f9-8fac-beeee107ce45.jpg)
> => Ele leva para a raíz do localhost:
> ![Captura de tela 2021-09-15 122913](https://user-images.githubusercontent.com/61397405/133464074-1889bb7e-184d-45ec-b56d-829094a11788.jpg)
> 
> -> Porém as configurações de diretório estão apontando para o subpasta onde instalei o sistema:
> ![Captura de tela 2021-09-15 123613](https://user-images.githubusercontent.com/61397405/133464567-b3c0995b-78c1-4dfb-9cda-0a2a386de3f6.jpg)
> ![Captura de tela 2021-09-15 123549](https://user-images.githubusercontent.com/61397405/133464569-2119348f-7bad-48d7-ad96-ab69c1737955.jpg)

If you have xampp you can configure a virtual host, that is in apache-> conf-> extra -> httpd-vhosts.conf
Examp:
NameVirtualHost *:81

<VirtualHost *:81>
    ServerAdmin admin@localhost.com
    DocumentRoot "Your root files"
<Directory "Your root files">
    AllowOverride All
    Require all granted
    Options Indexes FollowSymLinks
</Directory>
    ServerName localhost.com
    ServerAlias www.localhost.com
    ErrorLog "logs/localhost.com-error.log"
    CustomLog "logs/localhost.com-access.log" common
</VirtualHost>

then in the httpd.conf file in apache-> conf

add:
Listen 81

and test.

Remember  if you need change your file host in the system, the path is.

C:\Windows\System32\drivers\etc hosts file.

by default Apache will show you, localhost and the port in the browser:
http://localhost/ or http://localhost:81/  -  if you have configured the virtual host and:
127.0.0.1      localhost.com  -  If you have configured the hosts file

show in the browser 
http://localhost.com
