### ISSUE TITLE
Erro ao atualizar o banco de dados

### ISSUE THREAD

**Issue by pedroestevaodev** [pepiuox/PHP-GrapesJS#13]
Ao tentar atualizar o banco de dados, recebo sempre um erro, referente à imagem. Na hora de cadastrar a página tudo vai normal, porém os erros começam ao atualizar.

![Captura de tela 2021-09-14 144151](https://user-images.githubusercontent.com/61397405/133307740-e632dfe9-0490-4ea1-b864-b0cfbaf7de85.jpg)

**Comment by pepiuox** [comment]
> 
> 
> Ao tentar atualizar o banco de dados, recebo sempre um erro, referente à imagem. Na hora de cadastrar a página tudo vai normal, porém os erros começam ao atualizar.
> 
> ![Captura de tela 2021-09-14 144151](https://user-images.githubusercontent.com/61397405/133307740-e632dfe9-0490-4ea1-b864-b0cfbaf7de85.jpg)

Hello.
I just corrected the error and uploading files again.

Best regards.

**Comment by pepiuox** [comment]
If you have any comments write me, now I am advancing the CRUD system to edit tables without the need to make forms.

**Comment by pedroestevaodev** [comment]
Agora está atualizando perfeitamente. Qualquer erro que aparecer logo lhe aviso.

![IMG-20210915-WA0002.jpg](https://user-images.githubusercontent.com/61397405/133439476-fd186cd0-86b7-40e2-994a-3b201be0e21b.jpg)
