### ISSUE TITLE
Problema ao declarar variável $base

### ISSUE THREAD

**Issue by pedroestevaodev** [pepiuox/PHP-GrapesJS#14]
Após a atualização de ontem, resolvi reinstalar, e desta vez o css e scripts não funcionaram. Fui checar no inspecionar e vi que o caminho para os arquivos estava errado, com esse `favicon.ico`:
![Captura de tela 2021-09-15 170030](https://user-images.githubusercontent.com/61397405/133508055-1a8abc12-5706-415b-b623-5349f231863d.png)

E logo que fui checar a variável $base em dbconnection.php vi que a variável estava assim:
![Captura de tela 2021-09-15 165955](https://user-images.githubusercontent.com/61397405/133508252-bf9476ea-493f-4bf5-86dc-c76c7c91ad33.png)

A principio pensei que fosse um erro meu, e refiz a instalação, porém o erro persiste. Vou tentar verificar mais o código para ver se acho o erro.
![Captura de tela 2021-09-15 170049](https://user-images.githubusercontent.com/61397405/133508408-02fdaadd-b9ab-4f98-b825-c27d37fc90be.png)

**Comment by treborin** [comment]
Set $base var to this, @Pedro-Estevao:
`<?php $base = "../"; ?>`
