### ISSUE TITLE
Problema com os ícones do editor de imagem do GrapesJS

### ISSUE THREAD

**Issue by pedroestevaodev** [pepiuox/PHP-GrapesJS#15]
Fui dar uma fuçada no editor de páginas e ao abrir o editor de imagens me deparo com uma seção vazia, ou era o que eu achava até usar o inspecionar. Ele me mostrou o link da tag que deveria fornecer um ícone, imagino eu, porém ao pesquisar os links na web, os mesmos levam para páginas de erro 404.

-> ERRO ao abrir o link do svg:
![Captura de tela 2021-09-15 191327](https://user-images.githubusercontent.com/61397405/133516891-421bbd6f-3bbe-42a3-840a-550a9c3bb5b6.png)

-> Ao abrir o editor de imagens:
![Captura de tela 2021-09-15 190219](https://user-images.githubusercontent.com/61397405/133516896-20c21f1f-18f7-49c4-bc92-d979399be0be.png)

-> Ao inspecionar:
![Captura de tela 2021-09-15 190157](https://user-images.githubusercontent.com/61397405/133516907-4ef96103-290d-4fcd-a37b-052288e43a8e.png)

** O CKeditor do grapesjs também não está funcionando, mesmo com as variáveis iniciadas.

**Comment by pepiuox** [comment]
this error is solved, thanks for advice.
