### ISSUE TITLE
Installation fails on Step 5

### ISSUE THREAD

**Issue by hellaz** [pepiuox/PHP-GrapesJS#28]
Adding admin user fails on Step 5.
Register User button returns blank page.

**Comment by treborin** [comment]
Hi. Same issue here, @hellaz 
Any solution?

**Comment by treborin** [comment]
> Adding admin user fails on Step 5. Register User button returns blank page.

Ok. @hellaz . I found it.
On step 5, the installer creates the initial admin user (installUser.php file). And for that, it uses table uverify.
In my case, that table, uverify, was not created at all on Step 3.
The reason: that table uses a long row size, and you must to set your INNODB DEFAULT ROW FORMAT to Dynamic in MySQL (or MariaDB), and repeat the install process .

Hpe this helps you :)

**Comment by hellaz** [comment]
Not sure this caused the error to be honest, as my InnoDB is set global on Dynamic.
Still i've made a few changes on the SQL file, which might be helpful to replace installer/sql/page.sql file
[page.sql.txt](https://github.com/pepiuox/PHP-GrapesJS/files/9290973/page.sql.txt)
This executes flawlessly on PHPmyadmin
