### ISSUE TITLE
Installation on localhost

### ISSUE THREAD

**Issue by ruimngomes73** [pepiuox/PHP-GrapesJS#29]
Hi,

I´m having problems installing on localhost, at step 4, i don´t have any button to save the configuration or chance of editing any installation strings, they are not displayed.

**Comment by BdM5959** [comment]
Hi 
issue came up on line 172(install.php), due to a wrong sql column name.
The field name `SITE_PATH` is set as `SITE_PATH;`
To fix it add this php command in line 172 $update=str_replace(';','',$update);
then fix the others variables `SITE_PATH;` by removing the `;`
BdM

**Comment by pepiuox** [comment]
Hi, the files were updated, thanks for reporting bugs.
PePiuox
