### ISSUE TITLE
Error during installation  Unknown column 'SITE_PATH;'

### ISSUE THREAD

**Issue by MichaelDworkin** [pepiuox/PHP-GrapesJS#32]
Please correct the web page installer/install.php?step=4

<input type="text" class="form-control" id="SITE_PATH" name="**SITE_PATH;**"

 "SITE_PATH;" is incorrect 

"**SITE_PATH**" is correct

**Comment by dezigns333** [comment]
SITE_PATH; appears 6 times with a semicolon throughout the code on the page.

**Comment by pepiuox** [comment]
The files where updated, thanks for reporting bugs.
