### ISSUE TITLE
Installation won´t start

### ISSUE THREAD

**Issue by NeXxik91** [pepiuox/PHP-GrapesJS#36]
Hi, I just tried your project and the installation process doesn´t start.

**Comment by lucasheer** [comment]
You need to provide more details when having issues. This is not enough for developer to assist

**Comment by NeXxik91** [comment]
Hi, I just downloaded the zip, unzip iz into a root and then visited the
page. Nothing happened. No guide showed.

S pozdravem,
Tomáš Strejček
+420 731 306 092
CEO
GRAPA Studio s.r.o.


so 14. 10. 2023 v 2:08 odesílatel lucasheer ***@***.***>
napsal:

**Comment by NeXxik91** [comment]
Hi, I just downloaded the zip, unzip it into a root and then visited the page. Nothing happened. No guide showed.

**Comment by pepiuox** [comment]
Hello, 
What is the message that appears in the installation as a failure, in order to resolve it?

**Comment by NeXxik91** [comment]
Hello, nothing happened, blank window, no error.

**Comment by pepiuox** [comment]
Hi, 
Rename the file to config/dbconnection.php, then it should redirect you to the installation folder.
Now you can create a new database and do the installation.

**Comment by NeXxik91** [comment]
What file?

**Comment by NeXxik91** [comment]
Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in /srv/users/grapadevftp/apps/phpgrapejs/public/config/Database.php:87 Stack trace: #0 /srv/users/grapadevftp/apps/phpgrapejs/public/config/Database.php(87): mysqli->__construct('localhost', 'root', Object(SensitiveParameterValue), 'test_cms', '3306', '') #1 /srv/users/grapadevftp/apps/phpgrapejs/public/config/dbconnection.php(6): Database->MysqliConnection() #2 /srv/users/grapadevftp/apps/phpgrapejs/public/elements/view.php(6): require_once('/srv/users/grap...') #3 /srv/users/grapadevftp/apps/phpgrapejs/public/index.php(14): require_once('/srv/users/grap...') #4 {main} thrown in /srv/users/grapadevftp/apps/phpgrapejs/public/config/Database.php on line 87

**Comment by NeXxik91** [comment]
And of course I can follow all the files and set all the settings and create database and import the sql, but that´s  what the installer should do, right?

**Comment by pepiuox** [comment]
If you want to make the application work without doing an installation, you can enter the installer/sql/page.sql folder and export to the database, and change the configuration parameters of the config/server.php file
