### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by annearndt** [pepiuox/PHP-GrapesJS#37]
Hi, first sorry to disturb but I have a problem. I installed everything but when I will try I have this message 
"Fatal error: Uncaught Error: Undefined class constant 'PDO::MYSQL_ATTR_USE_BUFFERED_QUERY' in /home/xxx/public_html/config/dbconnection.php:5 Stack trace: #0 /home/xxx/public_html/elements/view.php(6): require_once() #1 /home/xxx/public_html/index.php(14): require_once('/home/xxx/p...') #2 {main} thrown in /home/xxx/public_html/config/dbconnection.php on line 5. "

How can I solve that? And thanks I really love your idea!

**Comment by pepiuox** [comment]
Hello, now update the files for install, try new again.

I hope the problem is resolved.
