### ISSUE TITLE
help me for my cms

### ISSUE THREAD

**Issue by vahidalvandi** [pepiuox/PHP-GrapesJS#6]
hello . mr , i have simple cms and want to use GrapesJs for page builder in article section . do your package can help me to use simply in my cms ?

**Comment by pepiuox** [comment]
Hello Vahid, if it can help you for your CMS, I am adding more features, I wish it had a better utility, I am also debugging files and libraries, but it is fully functional as is

**Comment by vahidalvandi** [comment]
thanks , i need same widget like price list ,... do i can connect widget to db ?

**Comment by pepiuox** [comment]
Hello, what do you want to add in your design, what type of data do you want to extract from your DB

**Comment by vahidalvandi** [comment]
i have simple cms and have cutome module like last carousel , in one category , i need drop carousel with category =1 then show recent carousel in category id .

i use laravel 8
