### ISSUE TITLE
help for install on local host 

### ISSUE THREAD

**Issue by mostafaecm** [pepiuox/PHP-GrapesJS#7]
hello 
i am new in github and i have problem to install php-grapesjs in localhost with this error 
"There is a user with the highest level of administration, delete that user, to continue with the installation."
please help tnx

**Comment by pepiuox** [comment]
Hello, you can use the last update that I uploaded, there are correction to many errors .

**Comment by mostafaecm** [comment]
hello and tnx for update but with the new update i have a new error:

Warning: mysqli::close(): Couldn't fetch mysqli in C:\laragon\www\***installer\install.php on line 182
User creation failed, check with support to continue with your registration.
thank you

**Comment by pepiuox** [comment]
> 
> 
> hello and tnx for update but with the new update i have a new error:
> 
> Warning: mysqli::close(): Couldn't fetch mysqli in C:\laragon\www***installer\install.php on line 182
> User creation failed, check with support to continue with your registration.
> thank you

Hello, I just updated and tested on my server and it works fine for me, please if you have any bugs let me know.
I made changes to not repeat a lot of code.

Thank You for your comments

**Comment by mostafaecm** [comment]
Hi again
There is still a problem with user registration for me and I tested on both the local and the server but the problem was not solved. And shows this error: User creation failed, check with support to continue with your registration.
Could it be a problem with the database format or the php version?

**Comment by pepiuox** [comment]
> Hi again
> There is still a problem with user registration for me and I tested on both the local and the server but the problem was not solved. And shows this error: User creation failed, check with support to continue with your registration.
> Could it be a problem with the database format or the php version?

Hello, 
The version of PHP I do not think is the problem, although if I know which version you use, I can do the test here, the other is the type of database is in utf8_bin, I have several versions of PHP installed but from 7 to 8 and higher.
What application do you use for your local server?

Best regards

**Comment by mostafaecm** [comment]
hello and tnx for answer
i use laragon for local app . but i test it in host server i give same error . php ver is 7.4 and databse format is utf8-generic-ci

**Comment by pepiuox** [comment]
> 
> 
> hello and tnx for answer
> i use laragon for local app . but i test it in host server i give same error . php ver is 7.4 and databse format is utf8-generic-ci

Hello
The problem in Laragon is in the mysql version, it does not support empty columns, have to be declared as NULL , so modify the .sql file and to see errors add a little more code, now if I install in Laragon.

Thank you for your patience.

Kind regards
