### ISSUE TITLE
Alert refresh causes problem

### ISSUE THREAD

**Issue by pedroestevaodev** [pepiuox/PHP-GrapesJS#9]
There would be a way to put a close button in place of refresh alerts. In some places the time of 5 seconds until it is good. However, when registering, when a PIN is provided, the alert disappears very quickly, as well as in some actions within the system.

**Comment by pepiuox** [comment]
> There would be a way to put a close button in place of refresh alerts. In some places the time of 5 seconds until it is good. However, when registering, when a PIN is provided, the alert disappears very quickly, as well as in some actions within the system.

Hello, 
Thank you for your comment, now the PIN is kept until the end of the installation, this PIN is used to access the system as part of security.

**Comment by pedroestevaodev** [comment]
Realizei a instalação novamente, porém o pin não foi fornecido. Agora surge um novo problema: 

![Captura de tela 2021-09-14 141222](https://user-images.githubusercontent.com/61397405/133303526-3c67a1d6-eda6-4bcf-aeae-6b2b4beb06e2.jpg)

**Comment by pepiuox** [comment]
> 
> 
> Realizei a instalação novamente, porém o pin não foi fornecido. Agora surge um novo problema:
> 
> ![Captura de tela 2021-09-14 141222](https://user-images.githubusercontent.com/61397405/133303526-3c67a1d6-eda6-4bcf-aeae-6b2b4beb06e2.jpg)

This is for security reasons, the files are renamed so that there are no reinstallation without authorization, the file with 32 characters would be the installer "install.php" and the one with 30 the class "installUser.php".
